disabled_rules:
  - line_length
  - force_cast
  - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Twitter-Redux/Models/MenuVCManager.swift 
  - Twitter-Redux/Models/TwitterUser.swift
  - Twitter-Redux/Models/Tweet.swift
  - Twitter-Redux/API/TwitterClient.swift
